shell = "zsh"

[templates]
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[plugins.compinit]
inline = "autoload -Uz compinit && zsh-defer compinit -d \"${ZCACHEDIR}/zcompdump-${ZSH_VERSION}\""

[plugins.local-sync]
inline = '''
target_dir="${ZDOTDIR}/sync"
if [[ -d "${target_dir}" ]]; then
   while IFS= read -r file; do
      source "${file}"
   done < <(find "${target_dir}" -type f -name "*.zsh" | sort)
fi
'''

[plugins.local-defer]
inline = '''
target_dir="${ZDOTDIR}/defer"
if [[ -d "${target_dir}" ]]; then
   while IFS= read -r file; do
      zsh-defer source "${file}"
   done < <(find "${target_dir}" -type f -name "*.zsh" | sort)
fi
'''
