# yaml-language-server: $schema=https://raw.githubusercontent.com/aquaproj/aqua/main/json-schema/aqua-yaml.json

registries:
  - type: standard
    ref: v4.417.0 # renovate: depName=aquaproj/aqua-registry

packages:
  - name: junegunn/fzf@v0.65.2
  - name: junegunn/fzf/fzf-tmux@v0.65.2

  - name: cli/cli@v2.80.0 # gh

  - name: BurntSushi/ripgrep@14.1.1
  - name: ajeetdsouza/zoxide@v0.9.8
  - name: eza-community/eza@v0.23.3
  - name: sharkdp/bat@v0.25.0
  - name: sharkdp/fd@v10.3.0

  - name: astral-sh/uv@0.8.22
